[tool.poetry]
name = "buf-plugin-python-betterproto"
version = "0.1.0"
description = ""
authors = ["Robert Pack <robstar.pack@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
betterproto = { version = "2.0.0b4", extras = ["compiler"] }
markupsafe = "2.0.1"
